name: 'GitHub Action Docker Container for Puppeteer Headful'
description: 'GitHub Action Docker Container for Puppeteer Headful with Emojis'
author: 'Pedro Portella'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'chevrons-up'
  color: 'yellow'
